# Generated by Django 5.2.1 on 2025-05-14 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('RPG', 'Role-Playing Game'), ('FPS', 'First-Person Shooter'), ('ADVENTURE', 'Adventure'), ('STRATEGY', 'Strategy'), ('SIMULATION', 'Simulation'), ('PUZZLE', 'Puzzle'), ('PLATFORMER', 'Platformer'), ('METROIDVANIA', 'Metroidvania'), ('VISUAL_NOVEL', 'Visual Novel'), ('OTHER', 'Other')], max_length=20)),
                ('ambiance', models.CharField(choices=[('POST_APOCALYPTIC', 'Post-Apocalyptic'), ('FANTASY', 'Fantasy'), ('SCI_FI', 'Science Fiction'), ('CYBERPUNK', 'Cyberpunk'), ('HORROR', 'Horror'), ('MYSTERY', 'Mystery'), ('HISTORICAL', 'Historical'), ('STEAMPUNK', 'Steampunk'), ('DREAMLIKE', 'Dreamlike'), ('DARK_FANTASY', 'Dark Fantasy'), ('OTHER', 'Other')], max_length=20)),
                ('keywords', models.CharField(help_text='Comma-separated keywords', max_length=200)),
                ('references', models.CharField(blank=True, help_text='Comma-separated references', max_length=200)),
                ('story_premise', models.TextField()),
                ('story_act1', models.TextField()),
                ('story_act2', models.TextField()),
                ('story_act3', models.TextField()),
                ('story_twist', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character_class', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('background', models.TextField()),
                ('gameplay', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='gameforge.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('CHARACTER', 'Character'), ('LOCATION', 'Location'), ('CONCEPT', 'Concept Art')], max_length=20)),
                ('image', models.ImageField(upload_to='game_images/')),
                ('prompt', models.TextField(help_text='The prompt used to generate this image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gameforge.game')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gameforge.game')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='gameforge.game')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
